# Chapter 02: Exercise 01

## 1. Preparing the data

In [1]:
import pandas as pd

- Load the data files:

In [2]:
ratings_file_path = '../../data/ml-1m/ratings.dat'
movies_file_path = '../../data/ml-1m/movies.dat'
users_file_path = '../../data/ml-1m/users.dat'

In [ ]:
ratings_df = pd.read_csv(ratings_file_path, sep='::', header=None, engine='python')
ratings_df.columns = ['UserID', 'MovieID', 'Rating', 'Timestamp']
ratings_df

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [13]:
users_df = pd.read_csv(users_file_path, sep='::', header=None, engine='python')
users_df.columns = ['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code']
users_df

      UserID Gender  Age  Occupation Zip-code
0          1      F    1          10    48067
1          2      M   56          16    70072
2          3      M   25          15    55117
3          4      M   45           7    02460
4          5      M   25          20    55455
...      ...    ...  ...         ...      ...
6035    6036      F   25          15    32603
6036    6037      F   45           1    76006
6037    6038      F   56           1    14706
6038    6039      F   45           0    01060
6039    6040      M   25           6    11106

[6040 rows x 5 columns]

In [14]:
movies_df = pd.read_csv(movies_file_path, sep='::', header=None, engine='python')
movies_df.columns = ['MovieID', 'Title', 'Genres']
movies_df

,MovieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

- View summary of the loaded DataFrames:

In [15]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   UserID     1000209 non-null  int64
 1   MovieID    1000209 non-null  int64
 2   Rating     1000209 non-null  int64
 3   Timestamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB

In [16]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   int64
 1   Gender      6040 non-null   object
 2   Age         6040 non-null   int64
 3   Occupation  6040 non-null   int64
 4   Zip-code    6040 non-null   object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB

In [17]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MovieID  3883 non-null   int64
 1   Title    3883 non-null   object
 2   Genres   3883 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.1+ KB

- Combine the DataFrames:

In [ ]:
# Check for unique values
print(
  f"No. of unique movie IDs: {movies_df['MovieID'].nunique()}",
  f"\nNo. of unique movie titles: {movies_df['Title'].nunique()}"
)

No. of unique movie IDs: 3883
No. of unique movie titles: 3883

In [29]:
# Create a mapping dictionary using movies_df['MovieID'] and movies_df['Title']
movieID_title = dict(
  zip(movies_df['MovieID'], movies_df['Title'])
)

# View the first 10 items in movieID_title
count = 0

for key, value in movieID_title.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: Toy Story (1995)
2: Jumanji (1995)
3: Grumpier Old Men (1995)
4: Waiting to Exhale (1995)
5: Father of the Bride Part II (1995)
6: Heat (1995)
7: Sabrina (1995)
8: Tom and Huck (1995)
9: Sudden Death (1995)
10: GoldenEye (1995)

In [31]:
# Duplicate ratings_df to create user_movie_ratings
user_movie_ratings = ratings_df.copy()

# Create a new column using .map()
user_movie_ratings['Title'] = user_movie_ratings['MovieID'].map(movieID_title)

user_movie_ratings.head()

   UserID  MovieID  Rating  Timestamp                                   Title
0       1     1193       5  978300760  One Flew Over the Cuckoo's Nest (1975)
1       1      661       3  978302109        James and the Giant Peach (1996)
2       1      914       3  978301968                     My Fair Lady (1964)
3       1     3408       4  978300275                  Erin Brockovich (2000)
4       1     2355       5  978824291                    Bug's Life, A (1998)

In [ ]:
# Add movie genres to user_movie_ratings