# Chapter 02: Exercise 01

## 1. Preparing the data

In [1]:
import pandas as pd

- Load the data files:

In [2]:
ratings_file_path = '../../data/ml-1m/ratings.dat'
movies_file_path = '../../data/ml-1m/movies.dat'
users_file_path = '../../data/ml-1m/users.dat'

In [3]:
ratings_df = pd.read_csv(ratings_file_path, sep='::', header=None, engine='python')
ratings_df.columns = ['UserID', 'MovieID', 'Rating', 'Timestamp']
ratings_df

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [4]:
users_df = pd.read_csv(users_file_path, sep='::', header=None, engine='python')
users_df.columns = ['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code']
users_df

      UserID Gender  Age  Occupation Zip-code
0          1      F    1          10    48067
1          2      M   56          16    70072
2          3      M   25          15    55117
3          4      M   45           7    02460
4          5      M   25          20    55455
...      ...    ...  ...         ...      ...
6035    6036      F   25          15    32603
6036    6037      F   45           1    76006
6037    6038      F   56           1    14706
6038    6039      F   45           0    01060
6039    6040      M   25           6    11106

[6040 rows x 5 columns]

In [5]:
movies_df = pd.read_csv(movies_file_path, sep='::', header=None, engine='python')
movies_df.columns = ['MovieID', 'Title', 'Genres']
movies_df

,MovieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

- View summary of the loaded DataFrames:

In [6]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   UserID     1000209 non-null  int64
 1   MovieID    1000209 non-null  int64
 2   Rating     1000209 non-null  int64
 3   Timestamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB

In [7]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   int64
 1   Gender      6040 non-null   object
 2   Age         6040 non-null   int64
 3   Occupation  6040 non-null   int64
 4   Zip-code    6040 non-null   object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB

In [8]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MovieID  3883 non-null   int64
 1   Title    3883 non-null   object
 2   Genres   3883 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.1+ KB

- Combine the DataFrames:

In [9]:
# Check for unique values
print(
  f"No. of unique movie IDs: {movies_df['MovieID'].nunique()}",
  f"\nNo. of unique movie titles: {movies_df['Title'].nunique()}"
)

No. of unique movie IDs: 3883
No. of unique movie titles: 3883

In [10]:
# Create a mapping dictionary using movies_df['MovieID'] and movies_df['Title']
movieID_title = dict(
  zip(movies_df['MovieID'], movies_df['Title'])
)

# View the first 10 items in movieID_title
count = 0

for key, value in movieID_title.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: Toy Story (1995)
2: Jumanji (1995)
3: Grumpier Old Men (1995)
4: Waiting to Exhale (1995)
5: Father of the Bride Part II (1995)
6: Heat (1995)
7: Sabrina (1995)
8: Tom and Huck (1995)
9: Sudden Death (1995)
10: GoldenEye (1995)

In [11]:
# Duplicate ratings_df to create user_movie_ratings
user_movie_ratings = ratings_df.copy()

# Create a new column using .map()
user_movie_ratings['Title'] = user_movie_ratings['MovieID'].map(movieID_title)

user_movie_ratings.head()

   UserID  MovieID  Rating  Timestamp                                   Title
0       1     1193       5  978300760  One Flew Over the Cuckoo's Nest (1975)
1       1      661       3  978302109        James and the Giant Peach (1996)
2       1      914       3  978301968                     My Fair Lady (1964)
3       1     3408       4  978300275                  Erin Brockovich (2000)
4       1     2355       5  978824291                    Bug's Life, A (1998)

In [12]:
# Add movie genres to user_movie_ratings
title_genre = dict(
  zip(movies_df['Title'], movies_df['Genres'])
)

count = 0

for key, value in title_genre.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

Toy Story (1995): Animation|Children's|Comedy
Jumanji (1995): Adventure|Children's|Fantasy
Grumpier Old Men (1995): Comedy|Romance
Waiting to Exhale (1995): Comedy|Drama
Father of the Bride Part II (1995): Comedy
Heat (1995): Action|Crime|Thriller
Sabrina (1995): Comedy|Romance
Tom and Huck (1995): Adventure|Children's
Sudden Death (1995): Action
GoldenEye (1995): Action|Adventure|Thriller

In [13]:
user_movie_ratings['Genres'] = user_movie_ratings['Title'].map(title_genre)

user_movie_ratings.head()

,UserID,MovieID,Rating,Timestamp,Title,Genres
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy

In [14]:
# Add gender of users to user_movie_ratings
userID_gender = dict(
  zip(users_df['UserID'], users_df['Gender'])
)

count = 0

for key, value in userID_gender.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: F
2: M
3: M
4: M
5: M
6: F
7: M
8: M
9: M
10: F

In [15]:
user_movie_ratings['Gender'] = user_movie_ratings['UserID'].map(userID_gender)

user_movie_ratings.head()

,UserID,MovieID,Rating,Timestamp,Title,Genres,Gender
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,F
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,F
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,F
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,F
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,F

In [16]:
# Add age of users to user_movie_ratings
userID_age = dict(
  zip(users_df['UserID'], users_df['Age'])
)

count = 0

for key, value in userID_age.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: 1
2: 56
3: 25
4: 45
5: 25
6: 50
7: 35
8: 25
9: 25
10: 35

In [17]:
user_movie_ratings['Age'] = user_movie_ratings['UserID'].map(userID_age)

user_movie_ratings.head()

,UserID,MovieID,Rating,Timestamp,Title,Genres,Gender,Age
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,F,1
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,F,1
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,F,1
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,F,1
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,F,1

In [18]:
# Add occupation of users to user_movie_ratings
userID_occupation = dict(
  zip(users_df['UserID'], users_df['Occupation'])
)

count = 0

for key, value in userID_occupation.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: 10
2: 16
3: 15
4: 7
5: 20
6: 9
7: 1
8: 12
9: 17
10: 1

In [19]:
user_movie_ratings['Occupation'] = user_movie_ratings['UserID'].map(userID_occupation)

user_movie_ratings.head()

,UserID,MovieID,Rating,Timestamp,Title,Genres,Gender,Age,Occupation
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,F,1,10
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,F,1,10
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,F,1,10
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,F,1,10
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,F,1,10

In [20]:
# Add zip code of users to user_movie_ratings
userID_zipcode = dict(
  zip(users_df['UserID'], users_df['Zip-code'])
)

count = 0

for key, value in userID_zipcode.items():
  if count < 10:
    print(f"{key}: {value}")
    count += 1
  else:
    break

1: 48067
2: 70072
3: 55117
4: 02460
5: 55455
6: 55117
7: 06810
8: 11413
9: 61614
10: 95370

In [21]:
user_movie_ratings['Zip-code'] = user_movie_ratings['UserID'].map(userID_zipcode)

user_movie_ratings.head()

,UserID,MovieID,Rating,Timestamp,Title,Genres,Gender,Age,Occupation,Zip-code
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,F,1,10,48067
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,F,1,10,48067
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,F,1,10,48067
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,F,1,10,48067
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,F,1,10,48067

- View a concise summary of the combined DataFrame:

In [22]:
user_movie_ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   UserID      1000209 non-null  int64
 1   MovieID     1000209 non-null  int64
 2   Rating      1000209 non-null  int64
 3   Timestamp   1000209 non-null  int64
 4   Title       1000209 non-null  object
 5   Genres      1000209 non-null  object
 6   Gender      1000209 non-null  object
 7   Age         1000209 non-null  int64
 8   Occupation  1000209 non-null  int64
 9   Zip-code    1000209 non-null  object
dtypes: int64(6), object(4)
memory usage: 76.3+ MB

- Rearrange the order of columns in the DataFrame:

In [23]:
column_order = ['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code', 'MovieID', 'Title', 'Genres', 'Timestamp', 'Rating']

user_movie_ratings = user_movie_ratings[column_order]

user_movie_ratings.head()

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Title,Genres,Timestamp,Rating
0,1,F,1,10,48067,1193,One Flew Over the Cuckoo's Nest (1975),Drama,978300760,5
1,1,F,1,10,48067,661,James and the Giant Peach (1996),Animation|Children's|Musical,978302109,3
2,1,F,1,10,48067,914,My Fair Lady (1964),Musical|Romance,978301968,3
3,1,F,1,10,48067,3408,Erin Brockovich (2000),Drama,978300275,4
4,1,F,1,10,48067,2355,"Bug's Life, A (1998)",Animation|Children's|Comedy,978824291,5

- Change the `dtype` in each column:

In [24]:
# Change the dtype in the gender column from object to category (unordered)
user_movie_ratings['Gender'] = user_movie_ratings['Gender'].astype('category')

print(f"Gender column Dtype: {user_movie_ratings['Gender'].dtype}")
print(f"Gender column categories: {user_movie_ratings['Gender'].cat.categories}")

Gender column Dtype: category
Gender column categories: Index(['F', 'M'], dtype='object')

In [25]:
# Change the dtype in the age column from int64 to category (ordered)
bins = [0, 12, 19, 34, 54, 64, 120]
# labels = ['Child', 'Teen', 'Young Adult', 'Middle Aged', 'Older Adult', 'Senior']
labels = ['Child (0 - 12)', 'Teen (13 - 19)', 'Young Adult (20 - 34)', 'Middle Aged (35 - 54)', 'Older Adult (55 - 64)', 'Senior (65+)']

user_movie_ratings['Age Group'] = pd.cut(
  user_movie_ratings['Age'],
  bins=bins,
  labels=labels,
  include_lowest=True
)

user_movie_ratings.head()

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Title,Genres,Timestamp,Rating,Age Group
0,1,F,1,10,48067,1193,One Flew Over the Cuckoo's Nest (1975),Drama,978300760,5,Child (0 - 12)
1,1,F,1,10,48067,661,James and the Giant Peach (1996),Animation|Children's|Musical,978302109,3,Child (0 - 12)
2,1,F,1,10,48067,914,My Fair Lady (1964),Musical|Romance,978301968,3,Child (0 - 12)
3,1,F,1,10,48067,3408,Erin Brockovich (2000),Drama,978300275,4,Child (0 - 12)
4,1,F,1,10,48067,2355,"Bug's Life, A (1998)",Animation|Children's|Comedy,978824291,5,Child (0 - 12)

In [26]:
age_column = user_movie_ratings.pop('Age')

column_order = ['UserID', 'Gender', 'Age Group', 'Occupation', 'Zip-code', 'MovieID', 'Title', 'Genres', 'Timestamp', 'Rating']
user_movie_ratings = user_movie_ratings[column_order]

print(user_movie_ratings.head())
print("-" * 50)
print(f"\nAge Group column Dtype: {user_movie_ratings['Age Group'].dtype}")
print(f"Age Group column categories: {user_movie_ratings['Age Group'].cat.categories}")
print(f"Are the Age Group column categories ordered? {user_movie_ratings['Age Group'].cat.ordered}")

   UserID Gender       Age Group  Occupation Zip-code  MovieID  \
0       1      F  Child (0 - 12)          10    48067     1193
1       1      F  Child (0 - 12)          10    48067      661
2       1      F  Child (0 - 12)          10    48067      914
3       1      F  Child (0 - 12)          10    48067     3408
4       1      F  Child (0 - 12)          10    48067     2355

                                    Title                        Genres  \
0  One Flew Over the Cuckoo's Nest (1975)                         Drama
1        James and the Giant Peach (1996)  Animation|Children's|Musical
2                     My Fair Lady (1964)               Musical|Romance
3                  Erin Brockovich (2000)                         Drama
4                    Bug's Life, A (1998)   Animation|Children's|Comedy

   Timestamp  Rating
0  978300760       5
1  978302109       3
2  978301968       3
3  978300275       4
4  978824291       5
--------------------------------------------------

Age Group column Dtype: category
Age Group column categories: Index(['Child (0 - 12)', 'Teen (13 - 19)', 'Young Adult (20 - 34)',
       'Middle Aged (35 - 54)', 'Older Adult (55 - 64)', 'Senior (65+)'],
      dtype='object')
Are the Age Group column categories ordered? True

In [ ]:
# Replace the values and change the dtype in the occupation column from int64 to category (unordered)

In [ ]:
# Change the dtype in the genres column from object to category (unordered)
# N.B: a movie can belong to more than one genre category

In [ ]:
# Change the dtype in the timestamp column from int64 to datetime64

In [ ]:
# Change the dtype in the rating column from int64 to category (ordered)